language: ruby

sudo: required

services:
  - docker

before_install:
  - gem install yaml-lint
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y dpkg
  - sudo apt-get install google-cloud-sdk
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.10.5/bin/linux/amd64/kubectl; chmod +x ./kubectl; sudo mv ./kubectl /usr/bin/
  - sudo apt-get install jq
  - echo $GCP_KEY_FILE | base64 -d > ./keyfile
  - gcloud auth activate-service-account -q $(jq -r .client_email keyfile) --key-file=./keyfile --project  $(jq -r .project_id keyfile)
  - rm ./keyfile

script:
  - echo "Cleaning up unused resources"
  
after_script:
  - gcloud container clusters list | grep sol-gke-travistest | awk '{print $1,$2}' | while read -r a b; do gcloud container clusters delete $a --zone $b --quiet; done
  - gcloud compute disks list | grep travis | sed 1d $rpt | while read -r a b c; do gcloud compute disks delete $a --zone $b --quiet; done
  - gcloud compute http-health-checks list | grep k8s | sed 1d $rpt | while read -r a b c; do gcloud compute http-health-checks delete $a --quiet; done
  - gcloud compute target-pools list | grep k8s | sed 1d $rpt | while read -r a b c; do gcloud compute target-pools delete $a --region $b --quiet; done
  - gcloud compute firewall-rules list | grep k8s | sed 1d $rpt | while read -r a b c; do gcloud compute firewall-rules delete $a --quiet; done
